# Generated by Django 4.1.3 on 2022-11-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('idcompetencia', models.IntegerField(db_column='IDCOMPETENCIA', primary_key=True, serialize=False)),
                ('nombrecompetencia', models.CharField(db_column='NOMBRECOMPETENCIA', max_length=255)),
            ],
            options={
                'db_table': 'competencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.IntegerField(db_column='IDEQUIPO', primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(db_column='NOMBREEQUIPO', max_length=255)),
                ('yearfundacion', models.CharField(db_column='YEARFUNDACION', max_length=255)),
                ('estadioequipo', models.CharField(db_column='ESTADIOEQUIPO', max_length=255)),
                ('ciudadequipo', models.CharField(db_column='CIUDADEQUIPO', max_length=255)),
                ('idTipoEquipo', models.IntegerField(db_column='IDTIPOEQUIPO')),
                ('urllogo', models.CharField(db_column='URLLOGO', max_length=255)),
                ('entrenador', models.CharField(db_column='ENTRENADOR', max_length=255)),
            ],
            options={
                'db_table': 'equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('idestadistica', models.IntegerField(db_column='IDESTADISTICA', primary_key=True, serialize=False)),
                ('rimtopartido', models.CharField(db_column='RIMTOPARTIDO', max_length=255)),
                ('tirosapuerta', models.CharField(db_column='TIROSAPUERTA', max_length=255)),
                ('pases', models.CharField(db_column='PASES', max_length=255)),
                ('regates', models.CharField(blank=True, db_column='REGATES', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estadistica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('nombrejugador', models.CharField(db_column='NOMBREJUGADOR', max_length=255)),
                ('edad', models.IntegerField(db_column='EDAD')),
                ('dorsaljugador', models.IntegerField(db_column='DORSALJUGADOR')),
                ('posicionjugador', models.CharField(db_column='POSICIONJUGADOR', max_length=255)),
                ('idjugador', models.IntegerField(db_column='IDJUGADOR', primary_key=True, serialize=False)),
                ('numerojugador', models.IntegerField(db_column='NUMEROJUGADOR')),
                ('escapitan', models.BooleanField(db_column='ESCAPITAN')),
                ('idequipo', models.IntegerField(db_column='IDEQUIPO')),
            ],
            options={
                'db_table': 'jugador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idpartido', models.IntegerField(db_column='IDPARTIDO', primary_key=True, serialize=False)),
                ('fechapartido', models.DateField(db_column='FECHAPARTIDO')),
                ('golescasa', models.IntegerField(db_column='GOLESCASA')),
                ('golesfuera', models.IntegerField(db_column='GOLESFUERA')),
            ],
            options={
                'db_table': 'partido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.IntegerField(db_column='IDPERMISO', primary_key=True, serialize=False)),
                ('estadopermiso', models.IntegerField(db_column='ESTADOPERMISO')),
            ],
            options={
                'db_table': 'permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(db_column='IDROL', primary_key=True, serialize=False)),
                ('tiporol', models.CharField(db_column='TIPOROL', max_length=255)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='IDUSUARIO', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NOMBREUSUARIO', max_length=255)),
                ('correousuario', models.CharField(db_column='CORREOUSUARIO', max_length=255)),
                ('passwordusuario', models.CharField(db_column='PASSWORDUSUARIO', max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idnoticia', models.IntegerField(db_column='IDNOTICIA', primary_key=True, serialize=False)),
                ('tiponoticia', models.CharField(db_column='TIPONOTICIA', max_length=255)),
                ('nombrenoticia', models.CharField(db_column='NOMBRENOTICIA', max_length=255)),
                ('equipo', models.CharField(db_column='EQUIPO', max_length=255)),
                ('idcompetencia', models.ForeignKey(blank=True, db_column='IDCOMPETENCIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.competencia')),
                ('idusuario', models.ForeignKey(blank=True, db_column='IDUSUARIO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.usuario')),
            ],
            options={
                'db_table': 'noticia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('idganador', models.IntegerField(db_column='IDGANADOR', primary_key=True, serialize=False)),
                ('nombreganador', models.CharField(db_column='NOMBREGANADOR', max_length=255)),
                ('idcompetencia', models.ForeignKey(blank=True, db_column='IDCOMPETENCIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.competencia')),
            ],
            options={
                'db_table': 'ganador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallenoticia',
            fields=[
                ('iddetalle', models.IntegerField(db_column='IDDETALLE', primary_key=True, serialize=False)),
                ('descripcionnoticia', models.CharField(db_column='DESCRIPCIONNOTICIA', max_length=9999)),
                ('fechanoticia', models.DateField(db_column='FECHANOTICIA')),
                ('urlimagen', models.CharField(db_column='URLIMAGEN', max_length=255)),
                ('idnoticia', models.ForeignKey(blank=True, db_column='IDNOTICIA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.noticia')),
            ],
            options={
                'db_table': 'detallenoticia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='competencia',
            name='idganador',
            field=models.ForeignKey(blank=True, db_column='IDGANADOR', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.ganador'),
        ),
        migrations.CreateModel(
            name='Posee',
            fields=[
                ('idrol', models.OneToOneField(db_column='IDROL', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.rol')),
                ('idusuario', models.ForeignKey(db_column='IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.usuario')),
            ],
            options={
                'db_table': 'posee',
                'managed': True,
                'unique_together': {('idrol', 'idusuario')},
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('idequipo', models.OneToOneField(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.equipo')),
                ('idcompetencia', models.ForeignKey(db_column='IDCOMPETENCIA', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.competencia')),
            ],
            options={
                'db_table': 'participa',
                'managed': True,
                'unique_together': {('idequipo', 'idcompetencia')},
            },
        ),
        migrations.CreateModel(
            name='Juega',
            fields=[
                ('idpartido', models.OneToOneField(db_column='IDPARTIDO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.partido')),
                ('idequipo', models.ForeignKey(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.equipo')),
            ],
            options={
                'db_table': 'juega',
                'managed': True,
                'unique_together': {('idpartido', 'idequipo')},
            },
        ),
        migrations.CreateModel(
            name='FormaParte',
            fields=[
                ('idjugador', models.OneToOneField(db_column='IDJUGADOR', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.jugador')),
                ('idequipo', models.ForeignKey(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.equipo')),
            ],
            options={
                'db_table': 'forma_parte',
                'managed': True,
                'unique_together': {('idjugador', 'idequipo')},
            },
        ),
        migrations.CreateModel(
            name='Define',
            fields=[
                ('idestadistica', models.OneToOneField(db_column='IDESTADISTICA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.estadistica')),
                ('idpartido', models.ForeignKey(db_column='IDPARTIDO', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.partido')),
            ],
            options={
                'db_table': 'define',
                'managed': True,
                'unique_together': {('idestadistica', 'idpartido')},
            },
        ),
        migrations.CreateModel(
            name='Conforma',
            fields=[
                ('idrol', models.OneToOneField(db_column='IDROL', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.rol')),
                ('idpermiso', models.ForeignKey(db_column='IDPERMISO', on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.permiso')),
            ],
            options={
                'db_table': 'conforma',
                'managed': True,
                'unique_together': {('idrol', 'idpermiso')},
            },
        ),
    ]
