# Generated by Django 4.1.3 on 2022-11-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('idcompetencia', models.IntegerField(db_column='IDCOMPETENCIA', primary_key=True, serialize=False)),
                ('nombrecompetencia', models.CharField(db_column='NOMBRECOMPETENCIA', max_length=255)),
            ],
            options={
                'db_table': 'competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallenoticia',
            fields=[
                ('iddetalle', models.IntegerField(db_column='IDDETALLE', primary_key=True, serialize=False)),
                ('descripcionnoticia', models.CharField(db_column='DESCRIPCIONNOTICIA', max_length=255)),
                ('fechanoticia', models.DateField(db_column='FECHANOTICIA')),
            ],
            options={
                'db_table': 'detallenoticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.IntegerField(db_column='IDEQUIPO', primary_key=True, serialize=False)),
                ('nombreequipo', models.CharField(db_column='NOMBREEQUIPO', max_length=255)),
                ('yearfundacion', models.CharField(db_column='YEARFUNDACION', max_length=255)),
                ('estadioequipo', models.CharField(db_column='ESTADIOEQUIPO', max_length=255)),
                ('ciudadequipo', models.CharField(db_column='CIUDADEQUIPO', max_length=255)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('idestadistica', models.IntegerField(db_column='IDESTADISTICA', primary_key=True, serialize=False)),
                ('rimtopartido', models.CharField(db_column='RIMTOPARTIDO', max_length=255)),
                ('tirosapuerta', models.CharField(db_column='TIROSAPUERTA', max_length=255)),
                ('pases', models.CharField(db_column='PASES', max_length=255)),
                ('regates', models.CharField(blank=True, db_column='REGATES', max_length=255, null=True)),
            ],
            options={
                'db_table': 'estadistica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ganador',
            fields=[
                ('idganador', models.IntegerField(db_column='IDGANADOR', primary_key=True, serialize=False)),
                ('nombreganador', models.CharField(db_column='NOMBREGANADOR', max_length=255)),
            ],
            options={
                'db_table': 'ganador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('nombrejugador', models.CharField(db_column='NOMBREJUGADOR', max_length=255)),
                ('fechanacimiento', models.CharField(db_column='FECHANACIMIENTO', max_length=255)),
                ('dorsaljugador', models.IntegerField(db_column='DORSALJUGADOR')),
                ('posicionjugador', models.CharField(db_column='POSICIONJUGADOR', max_length=255)),
                ('idjugador', models.IntegerField(db_column='IDJUGADOR', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jugador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idnoticia', models.IntegerField(db_column='IDNOTICIA', primary_key=True, serialize=False)),
                ('tiponoticia', models.CharField(db_column='TIPONOTICIA', max_length=255)),
                ('nombrenoticia', models.CharField(db_column='NOMBRENOTICIA', max_length=255)),
            ],
            options={
                'db_table': 'noticia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idpartido', models.IntegerField(db_column='IDPARTIDO', primary_key=True, serialize=False)),
                ('fechapartido', models.DateField(db_column='FECHAPARTIDO')),
                ('golescasa', models.IntegerField(db_column='GOLESCASA')),
                ('golesfuera', models.IntegerField(db_column='GOLESFUERA')),
            ],
            options={
                'db_table': 'partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idpermiso', models.IntegerField(db_column='IDPERMISO', primary_key=True, serialize=False)),
                ('estadopermiso', models.IntegerField(db_column='ESTADOPERMISO')),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(db_column='IDROL', primary_key=True, serialize=False)),
                ('tiporol', models.CharField(db_column='TIPOROL', max_length=255)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='IDUSUARIO', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='NOMBREUSUARIO', max_length=255)),
                ('correousuario', models.CharField(db_column='CORREOUSUARIO', max_length=255)),
                ('passwordusuario', models.CharField(db_column='PASSWORDUSUARIO', max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conforma',
            fields=[
                ('idrol', models.OneToOneField(db_column='IDROL', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.rol')),
            ],
            options={
                'db_table': 'conforma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Define',
            fields=[
                ('idestadistica', models.OneToOneField(db_column='IDESTADISTICA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.estadistica')),
            ],
            options={
                'db_table': 'define',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaParte',
            fields=[
                ('idjugador', models.OneToOneField(db_column='IDJUGADOR', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.jugador')),
            ],
            options={
                'db_table': 'forma_parte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juega',
            fields=[
                ('idpartido', models.OneToOneField(db_column='IDPARTIDO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.partido')),
            ],
            options={
                'db_table': 'juega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('idequipo', models.OneToOneField(db_column='IDEQUIPO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.equipo')),
            ],
            options={
                'db_table': 'participa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posee',
            fields=[
                ('idrol', models.OneToOneField(db_column='IDROL', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='webApp.rol')),
            ],
            options={
                'db_table': 'posee',
                'managed': False,
            },
        ),
    ]
