# Generated by Django 4.1.3 on 2022-11-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detallenoticia',
            fields=[
                ('iddetalle', models.IntegerField(db_column='IDDETALLE', primary_key=True, serialize=False)),
                ('descripcionnoticia', models.CharField(db_column='DESCRIPCIONNOTICIA', max_length=255)),
                ('fechanoticia', models.DateField(db_column='FECHANOTICIA')),
                ('imagennoticia', models.ImageField(upload_to='imagenes/', verbose_name='IMAGENNOTICIA')),
            ],
            options={
                'db_table': 'detallenoticia',
                'managed': False,
            },
        ),
    ]
