# Generated by Django 4.1.3 on 2022-11-28 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_detallenoticia_idequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='idequipo',
            field=models.ForeignKey(blank=True, db_column='IDEQUIPO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.equipo'),
        ),
    ]
