# Generated by Django 4.1.3 on 2022-11-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_jugador_idequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='equipo',
        ),
    ]
