# Generated by Django 4.1.3 on 2022-11-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_jugador_idequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='dorsaljugador',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='equipo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='etiqueta',
            field=models.CharField(blank=True, db_column='ETIQUETA', max_length=255, null=True),
        ),
    ]
