# Generated by Django 4.1.3 on 2022-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_remove_jugador_dorsaljugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dorsaljugador',
            field=models.IntegerField(blank=True, db_column='DORSALJUGADOR', null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='equipo',
            field=models.CharField(blank=True, db_column='EQUIPO', max_length=255, null=True),
        ),
    ]
