# Generated by Django 4.1.3 on 2022-11-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_jugador_dorsaljugador_noticia_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='dorsaljugador',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='equipo',
        ),
    ]
