# Generated by Django 4.1.3 on 2022-12-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_noticia_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='noticia',
            name='idequipo',
            field=models.ForeignKey(blank=True, db_column='IDEQUIPO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webApp.equipo'),
        ),
    ]
